/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/EmployeeRecords': RouteRecordInfo<'/EmployeeRecords', '/EmployeeRecords', Record<never, never>, Record<never, never>>,
    '/Employees': RouteRecordInfo<'/Employees', '/Employees', Record<never, never>, Record<never, never>>,
    '/Entries': RouteRecordInfo<'/Entries', '/Entries', Record<never, never>, Record<never, never>>,
    '/Events': RouteRecordInfo<'/Events', '/Events', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Records': RouteRecordInfo<'/Records', '/Records', Record<never, never>, Record<never, never>>,
    '/RegulariseRecord': RouteRecordInfo<'/RegulariseRecord', '/RegulariseRecord', Record<never, never>, Record<never, never>>,
    '/Users': RouteRecordInfo<'/Users', '/Users', Record<never, never>, Record<never, never>>,
  }
}
